# Workflow to automatically build and release an Android Plugin with GDExtension capabilities
name: Build ARCore Plugin

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch: # Enables manual "Run workflow" button in GitHub Actions tab

jobs:
  build:
    name: Building for Android (Ubuntu 24.04)
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: repo
          submodules: "recursive"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: "temurin"

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r23c
          link-to-sdk: true

      - name: Install SCons
        run: |
          python -m pip install scons==4.0.0

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v3

      - name: Create libgodot-cpp Android templates
        run: |
          cd $GITHUB_WORKSPACE/repo/godot-cpp
          scons platform=android target=template_debug arch=arm64 custom_api_file=../thirdparty/godot_cpp_extension_api/extension_api.json
          scons platform=android target=template_release arch=arm64 custom_api_file=../thirdparty/godot_cpp_extension_api/extension_api.json
          cd $GITHUB_WORKSPACE

      - name: Grant execute permission for Gradle
        run: chmod +x $GITHUB_WORKSPACE/repo/gradlew

      - name: Assemble the plugin
        run: |
          cd $GITHUB_WORKSPACE/repo
          ./gradlew assemble

      - name: Upload build files
        uses: actions/upload-artifact@v4
        with:
          name: arcore-build
          path: |
            repo/**/*.aar
            repo/**/*.gdip
          if-no-files-found: error # Ensures build fails early if no files were generated

  release:
    if: github.event_name == 'push' && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags'))
    name: Assembling the asset
    runs-on: ubuntu-24.04
    needs: build

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: arcore-build
          path: ./aar-output

      - name: List downloaded files
        run: ls -R ./aar-output
